/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blackholegame;

/**
 *
 * @author Totu-vostro-5640
 */
public class BlackHoleGame extends javax.swing.JFrame {
    private GameModel model;
    private BoardPanel boardPanel;


    
    public BlackHoleGame() {
        initComponents();
        model = new GameModel(7);
        boardPanel = new BoardPanel(model);

        boardPanelContainer.setLayout(new java.awt.BorderLayout());
        boardPanelContainer.removeAll();
        boardPanelContainer.add(boardPanel, java.awt.BorderLayout.CENTER);
        boardPanelContainer.revalidate();
        boardPanelContainer.repaint();

        sizeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"5 x 5", "7 x 7", "9 x 9"}));
        sizeCombo.setSelectedIndex(1);

        newGameBtn.addActionListener(e -> restartFromUI());
        sizeCombo.addActionListener(e -> restartFromUI());


        setStatus();
        pack();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                int confirm = javax.swing.JOptionPane.showConfirmDialog(
                    null,
                    "Are you sure you want to exit the game?",
                    "Exit Confirmation",
                    javax.swing.JOptionPane.YES_NO_OPTION
                );
                if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });


    }
    
    public void setStatus() {
        statusLabel.setText(String.format("Turn: %s   |   Score  P1: %d  P2: %d   |   Goal: %d",
            model.currentPlayer == Player.P1 ? "Player 1" : "Player 2",
            model.scoreP1, model.scoreP2, model.targetScore()));
    }

    public void restartFromUI() {
        try {
            int n = selectedBoardSize();

            // recreate the model and boardPanel fully
            model = new GameModel(n);
            boardPanel = new BoardPanel(model);

            // refresh container
            boardPanelContainer.removeAll();
            boardPanelContainer.setLayout(new java.awt.BorderLayout());
            boardPanelContainer.add(boardPanel, java.awt.BorderLayout.CENTER);
            boardPanelContainer.revalidate();
            boardPanelContainer.repaint();

            setStatus();
            pack();
            setLocationRelativeTo(null);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "An error occurred while restarting the game:\n" + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }


    private int selectedBoardSize() {
        int idx = sizeCombo.getSelectedIndex();
        if (idx < 0) idx = 1;
        int n = 7;
        if (idx == 0) n = 5;
        if (idx == 1) n = 7;
        if (idx == 2) n = 9;
        return n;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame3 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jFrame2 = new javax.swing.JFrame();
        jFrame1 = new javax.swing.JFrame();
        boardPanelContainer = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sizeCombo = new javax.swing.JComboBox<>();
        newGameBtn = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuRestart = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuHowToPlay = new javax.swing.JMenuItem();

        jInternalFrame3.setVisible(true);

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jFrame2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFrame2WindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boardPanelContainer.setName(""); // NOI18N
        boardPanelContainer.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("jLabel1");
        statusLabel.setName("statusLabel"); // NOI18N
        boardPanelContainer.add(statusLabel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(boardPanelContainer, java.awt.BorderLayout.PAGE_END);

        sizeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 x 5", "7 x 7", "9 x 9", " " }));
        sizeCombo.setToolTipText("jComboBox1");
        jPanel1.add(sizeCombo);

        newGameBtn.setText("New Game");
        jPanel1.add(newGameBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        menuUser.setText("User");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuUser.add(menuLogin);

        menuRestart.setText("Restart Game");
        menuRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRestartActionPerformed(evt);
            }
        });
        menuUser.add(menuRestart);

        jMenuBar2.add(menuUser);

        menuHelp.setText("Help");

        menuHowToPlay.setText("How to Play");
        menuHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHowToPlayActionPerformed(evt);
            }
        });
        menuHelp.add(menuHowToPlay);

        jMenuBar2.add(menuHelp);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRestartActionPerformed
        restartFromUI();
    }//GEN-LAST:event_menuRestartActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        javax.swing.JTextField usernameField = new javax.swing.JTextField();
        javax.swing.JPasswordField passwordField = new javax.swing.JPasswordField();
        Object[] message = {
            "Username:", usernameField,
            "Password:", passwordField
        };

        int option = javax.swing.JOptionPane.showConfirmDialog(
                this, message, "Login", javax.swing.JOptionPane.OK_CANCEL_OPTION);

        if (option == javax.swing.JOptionPane.OK_OPTION) {
            String username = usernameField.getText();
            String password = new String(passwordField.getPassword());
            if (username.isEmpty() || password.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Please fill in all fields.",
                    "Warning",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Welcome, " + username + "!",
                    "Login Successful",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_menuLoginActionPerformed

    private void menuHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHowToPlayActionPerformed
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "🌀 BLACK HOLE GAME RULES 🌀\n\n"
            + "• The game is played on a square board (5x5, 7x7, or 9x9).\n"
            + "• Player 1 controls red ships, Player 2 controls blue ships.\n"
            + "• The black hole is in the center of the board.\n"
            + "• Ships slide until they reach the edge, another ship, or the hole.\n"
            + "• A player wins when half of their ships fall into the black hole.\n"
            + "• After a game ends, a new one starts automatically.",
            "How to Play",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

    }//GEN-LAST:event_menuHowToPlayActionPerformed

    private void jFrame2WindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame2WindowClosed
        int result = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit?",
            "Exit Confirmation",
            javax.swing.JOptionPane.OK_CANCEL_OPTION
        );

        if (result == javax.swing.JOptionPane.OK_OPTION) {
            dispose();
        }

    }//GEN-LAST:event_jFrame2WindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackHoleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackHoleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackHoleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackHoleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackHoleGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardPanelContainer;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuHowToPlay;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuRestart;
    private javax.swing.JMenu menuUser;
    private javax.swing.JButton newGameBtn;
    private javax.swing.JComboBox<String> sizeCombo;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
